package ru.zero.util.render.backends.vk;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

@Environment(EnvType.CLIENT)
final class VulkanGlassShaders {
   private VulkanGlassShaders() {
   }

   // Fullscreen blit vertex shader. Draws a fullscreen triangle via a 3-vertex static
   // buffer (Position.xy = clip-space coords, z unused). UV = Position.xy*0.5+0.5.
   static final String BLIT_VERT =
         "#version 450\n"
         + "layout(location=0) in vec2 Position;\n"
         + "layout(location=0) out vec2 texCoord;\n"
         + "void main(){\n"
         + "    texCoord = Position * 0.5 + 0.5;\n"
         + "    gl_Position = vec4(Position, 0.0, 1.0);\n"
         + "}\n";

   // Separable Gaussian blur (matches assets/aetherial/shaders/program/blur.fsh).
   // std140 Weights array: each element occupies 16 bytes (std140 array stride).
   static final String BLUR_FRAG =
         "#version 450\n"
         + "layout(set=0, binding=0) uniform sampler2D DiffuseSampler;\n"
         + "layout(set=0, binding=1, std140) uniform SamplerInfo { vec2 OutSize; vec2 InSize; };\n"
         + "layout(set=0, binding=2, std140) uniform Config { vec4 Params; float Weights[193]; };\n"
         + "layout(location=0) in vec2 texCoord;\n"
         + "layout(location=0) out vec4 fragColor;\n"
         + "void main(){\n"
         + "    int radius = int(Params.z + 0.5);\n"
         + "    radius = clamp(radius, 0, 192);\n"
         + "    vec2 delta = Params.xy / OutSize;\n"
         + "    vec4 sum = texture(DiffuseSampler, texCoord) * Weights[0];\n"
         + "    for (int i = 1; i <= radius; ++i) {\n"
         + "        float w = Weights[i];\n"
         + "        vec2 offs = delta * float(i);\n"
         + "        sum += texture(DiffuseSampler, texCoord + offs) * w;\n"
         + "        sum += texture(DiffuseSampler, texCoord - offs) * w;\n"
         + "    }\n"
         + "    fragColor = sum;\n"
         + "}\n";

   // Liquid glass composite (matches assets/aetherial/shaders/program/liquid_glass_gui.fsh).
   // Sampler0 = backdrop (MC framebuffer captured into a shared VK image), Sampler1-5 =
   // precomputed blurred backdrops per radius. UBO layouts mirror the GL std140 layout
   // produced by AetherialGlassUniforms.uploadSharedUniforms/uploadWidgetInfo.
   static final String GLASS_FRAG =
         "#version 450\n"
         + "layout(set=0, binding=0) uniform sampler2D Sampler0;\n"
         + "layout(set=0, binding=1) uniform sampler2D Sampler1;\n"
         + "layout(set=0, binding=2) uniform sampler2D Sampler2;\n"
         + "layout(set=0, binding=3) uniform sampler2D Sampler3;\n"
         + "layout(set=0, binding=4) uniform sampler2D Sampler4;\n"
         + "layout(set=0, binding=5) uniform sampler2D Sampler5;\n"
         + "layout(set=0, binding=6, std140) uniform SamplerInfo { vec2 OutSize; vec2 InSize; };\n"
         + "layout(set=0, binding=7, std140) uniform CustomUniforms {\n"
         + "    float Time;\n"
         + "    vec4 Mouse;\n"
         + "    float ScreenWantsBlur;\n"
         + "    vec3 RIM_LIGHT_VEC;\n"
         + "    vec4 RIM_LIGHT_COLOR;\n"
         + "    float EPS_PIX;\n"
         + "    float DebugStep;\n"
         + "    float Pixelated;\n"
         + "    float PixelGridSize;\n"
         + "    float HoverScalePx;\n"
         + "    float FocusScalePx;\n"
         + "    float FocusBorderWidthPx;\n"
         + "    float FocusBorderIntensity;\n"
         + "    float FocusBorderSpeed;\n"
         + "};\n"
         + "#define MAX_WIDGETS 64\n"
         + "layout(set=0, binding=8, std140) uniform WidgetInfo {\n"
         + "    float Count;\n"
         + "    vec4 Rects[MAX_WIDGETS];\n"
         + "    vec4 Rads[MAX_WIDGETS];\n"
         + "    vec4 Tints[MAX_WIDGETS];\n"
         + "    vec4 Optics0[MAX_WIDGETS];\n"
         + "    vec4 Optics1[MAX_WIDGETS];\n"
         + "    vec4 Optics2[MAX_WIDGETS];\n"
         + "    vec4 Smoothings[MAX_WIDGETS];\n"
         + "    vec4 ScissorRects[MAX_WIDGETS];\n"
         + "    vec4 Shadow0[MAX_WIDGETS];\n"
         + "    vec4 ShadowColor[MAX_WIDGETS];\n"
         + "    vec4 Extra0[MAX_WIDGETS];\n"
         + "};\n"
         + "layout(set=0, binding=9, std140) uniform BgConfig {\n"
         + "    float ShadowExpand;\n"
         + "    float ShadowFactor;\n"
         + "    vec2 ShadowOffset;\n"
         + "};\n"
         + "layout(location=0) out vec4 fragColor;\n"
         + "struct SDFResult { float dist; vec2 normal; float aspect; int index; };\n"
         + "vec2 screenToUV(vec2 screen, vec2 res) { return (screen.xy - 0.5 * res.xy) / res.y; }\n"
         + "vec3 sdgBox(in vec2 p, in vec2 b, vec4 ra) {\n"
         + "    ra.xy = (p.x > 0.0) ? ra.xy : ra.zw;\n"
         + "    float r = (p.y > 0.0) ? ra.x : ra.y;\n"
         + "    vec2 w = abs(p) - (b - r);\n"
         + "    vec2 s = vec2(p.x < 0.0 ? -1.0 : 1.0, p.y < 0.0 ? -1.0 : 1.0);\n"
         + "    float g = max(w.x, w.y);\n"
         + "    vec2 q = max(w, 0.0);\n"
         + "    float l = length(q);\n"
         + "    float dist = (g > 0.0) ? l - r : g - r;\n"
         + "    vec2 ew = vec2(exp(w.x / 0.008), exp(w.y / 0.008)) + 1e-6;\n"
         + "    vec2 nInside = normalize(ew);\n"
         + "    vec2 n = (g > 0.0) ? (q / max(l, 1e-6)) : nInside;\n"
         + "    return vec3(dist, s * n);\n"
         + "}\n"
         + "SDFResult opSmoothUnion(in SDFResult a, in SDFResult b, in float k) {\n"
         + "    if (k == 0.0) return (a.dist < b.dist) ? a : b;\n"
         + "    float h = clamp(0.5 + 0.5 * (a.dist - b.dist) / k, 0.0, 1.0);\n"
         + "    float d = mix(a.dist, b.dist, h) - k * h * (1.0 - h);\n"
         + "    vec2 n = normalize(mix(a.normal, b.normal, h));\n"
         + "    float aspect = mix(a.aspect, b.aspect, h);\n"
         + "    int index = (a.dist < b.dist) ? a.index : b.index;\n"
         + "    return SDFResult(d, n, aspect, index);\n"
         + "}\n"
         + "SDFResult opHardUnion(SDFResult a, SDFResult b) { return (a.dist < b.dist) ? a : b; }\n"
         + "SDFResult opHardSubtract(SDFResult a, SDFResult b) {\n"
         + "    float d = max(a.dist, -b.dist);\n"
         + "    if (d == a.dist) return a;\n"
         + "    return SDFResult(d, -b.normal, a.aspect, a.index);\n"
         + "}\n"
         + "vec4 sampleBlur(int idx, vec2 uv) {\n"
         + "    uv = clamp(uv, 0.0, 1.0);\n"
         + "    if (idx <= 0) return texture(Sampler1, uv);\n"
         + "    if (idx == 1) return texture(Sampler2, uv);\n"
         + "    if (idx == 2) return texture(Sampler3, uv);\n"
         + "    if (idx == 3) return texture(Sampler4, uv);\n"
         + "    return texture(Sampler5, uv);\n"
         + "}\n"
         + "SDFResult fieldWidgets(vec2 p, vec2 inSize, vec2 fragCoord) {\n"
         + "    int n = int(Count + 0.5);\n"
         + "    if (n == 0) return SDFResult(1e6, vec2(0.0), 1.0, -1);\n"
         + "    SDFResult pos = SDFResult(1e6, vec2(0.0), 1.0, -1);\n"
         + "    bool hasPos = false;\n"
         + "    for (int i = 0; i < MAX_WIDGETS; i++) {\n"
         + "        if (i >= n) break;\n"
         + "        if (Smoothings[i].x < 0.0) continue;\n"
         + "        vec4 sc = ScissorRects[i];\n"
         + "        if (fragCoord.x < sc.x || fragCoord.y < sc.y || fragCoord.x > sc.z || fragCoord.y > sc.w) continue;\n"
         + "        vec4 rc = Rects[i];\n"
         + "        vec4 rr = Rads[i];\n"
         + "        vec2 cPx = vec2(rc.x + 0.5 * rc.z, rc.y + 0.5 * rc.w);\n"
         + "        vec2 c = screenToUV(cPx, inSize);\n"
         + "        vec2 b = 0.5 * vec2(rc.z, rc.w) / inSize.y;\n"
         + "        vec4 rad = rr / inSize.y;\n"
         + "        vec3 g = sdgBox(p - c, b, rad);\n"
         + "        vec4 extra = Extra0[i];\n"
         + "        float scaleOff = (HoverScalePx * extra.y + FocusScalePx * extra.z) / inSize.y;\n"
         + "        float dist = g.x - scaleOff;\n"
         + "        float aspect = min(rc.z, rc.w) / max(rc.z, rc.w);\n"
         + "        SDFResult s = SDFResult(dist, g.yz, aspect, i);\n"
         + "        if (!hasPos) { pos = s; hasPos = true; }\n"
         + "        else { pos = opSmoothUnion(pos, s, Smoothings[i].x); }\n"
         + "    }\n"
         + "    SDFResult f = pos;\n"
         + "    for (int i = 0; i < MAX_WIDGETS; i++) {\n"
         + "        if (i >= n) break;\n"
         + "        if (Smoothings[i].x >= 0.0) continue;\n"
         + "        vec4 sc = ScissorRects[i];\n"
         + "        if (fragCoord.x < sc.x || fragCoord.y < sc.y || fragCoord.x > sc.z || fragCoord.y > sc.w) continue;\n"
         + "        vec4 rc = Rects[i];\n"
         + "        vec4 rr = Rads[i];\n"
         + "        vec2 cPx = vec2(rc.x + 0.5 * rc.z, rc.y + 0.5 * rc.w);\n"
         + "        vec2 c = screenToUV(cPx, inSize);\n"
         + "        vec2 b = 0.5 * vec2(rc.z, rc.w) / inSize.y;\n"
         + "        vec4 rad = rr / inSize.y;\n"
         + "        vec3 g = sdgBox(p - c, b, rad);\n"
         + "        vec4 extra = Extra0[i];\n"
         + "        float scaleOff = (HoverScalePx * extra.y + FocusScalePx * extra.z) / inSize.y;\n"
         + "        float dist = g.x - scaleOff;\n"
         + "        float aspect = min(rc.z, rc.w) / max(rc.z, rc.w);\n"
         + "        SDFResult s = SDFResult(dist, g.yz, aspect, i);\n"
         + "        float repulsion = -Smoothings[i].x;\n"
         + "        SDFResult se = SDFResult(s.dist - repulsion, s.normal, s.aspect, s.index);\n"
         + "        f = opHardSubtract(f, se);\n"
         + "        f = opHardUnion(f, s);\n"
         + "    }\n"
         + "    return f;\n"
         + "}\n"
         + "void main() {\n"
         + "    vec2 inSize = InSize;\n"
         + "    if (inSize.x <= 0.0 || inSize.y <= 0.0) inSize = vec2(textureSize(Sampler0, 0));\n"
         + "    vec2 coord = gl_FragCoord.xy;\n"
         + "    vec2 uv = coord / inSize;\n"
         + "    vec3 base = texture(Sampler0, uv).rgb;\n"
         + "    vec3 baseShadowed = base;\n"
         + "    int n = int(Count + 0.5);\n"
         + "    for (int i = 0; i < MAX_WIDGETS; i++) {\n"
         + "        if (i >= n) break;\n"
         + "        vec4 sc = ScissorRects[i];\n"
         + "        if (coord.x < sc.x || coord.y < sc.y || coord.x > sc.z || coord.y > sc.w) continue;\n"
         + "        vec4 rc = Rects[i];\n"
         + "        vec4 rr = Rads[i];\n"
         + "        vec2 cPx = vec2(rc.x + 0.5 * rc.z, rc.y + 0.5 * rc.w);\n"
         + "        vec2 pShadow = screenToUV(coord + Shadow0[i].zw, inSize);\n"
         + "        vec2 c = screenToUV(cPx, inSize);\n"
         + "        vec2 b = 0.5 * vec2(rc.z, rc.w) / inSize.y;\n"
         + "        vec4 rad = rr / inSize.y;\n"
         + "        vec3 g = sdgBox(pShadow - c, b, rad);\n"
         + "        float expand = max(Shadow0[i].x, 1e-4);\n"
         + "        float factor = Shadow0[i].y;\n"
         + "        float sh = exp(-abs(g.x) * inSize.y / expand) * 0.6 * factor;\n"
         + "        vec3 scol = ShadowColor[i].rgb;\n"
         + "        float sa = clamp(ShadowColor[i].a * sh, 0.0, 1.0);\n"
         + "        baseShadowed = mix(baseShadowed, scol, sa);\n"
         + "    }\n"
         + "    vec2 p = screenToUV(coord, inSize);\n"
         + "    SDFResult f = fieldWidgets(p, inSize, coord);\n"
         + "    float merged = f.dist;\n"
         + "    int STEP = int(DebugStep + 0.5);\n"
         + "    if (STEP <= 1) {\n"
         + "        vec3 col = (merged > 0.0) ? vec3(0.9, 0.6, 0.3) : vec3(0.65, 0.85, 1.0);\n"
         + "        col *= 1.0 - exp(-0.03 * abs(merged) * inSize.y);\n"
         + "        fragColor = vec4(col, 1.0);\n"
         + "        return;\n"
         + "    }\n"
         + "    if (merged >= 0.0) { fragColor = vec4(baseShadowed, 1.0); return; }\n"
         + "    vec2 coordPix = coord;\n"
         + "    if (Pixelated > 0.5) { coordPix = floor(coord / PixelGridSize) * PixelGridSize + 0.5 * PixelGridSize; }\n"
         + "    vec2 uvPix = coordPix / inSize;\n"
         + "    int idx = f.index;\n"
         + "    vec4 o0 = Optics0[idx];\n"
         + "    vec4 o1 = Optics1[idx];\n"
         + "    vec4 o2 = Optics2[idx];\n"
         + "    vec4 tint = Tints[idx];\n"
         + "    vec4 extra = Extra0[idx];\n"
         + "    float refThickness = o0.x;\n"
         + "    float refFactor = o0.y;\n"
         + "    float refDisp = o0.z;\n"
         + "    float refFresRange = o0.w;\n"
         + "    float refFresHard = o1.x / 100.0;\n"
         + "    float refFresFac = o1.y / 100.0;\n"
         + "    float glareRange = o1.z;\n"
         + "    float glareHard = o1.w / 100.0;\n"
         + "    float hoverK = extra.y;\n"
         + "    float focusK = extra.z;\n"
         + "    int blurIndex = int(extra.x + 0.5);\n"
         + "    vec2 normal = f.normal;\n"
         + "    float nlen = length(normal);\n"
         + "    if (nlen > 1e-6) normal /= nlen;\n"
         + "    float nmerged = -merged * inSize.y;\n"
         + "    float xR = 1.0 - nmerged / max(refThickness, 1e-6);\n"
         + "    float thetaI = asin(pow(xR, 2.0));\n"
         + "    float thetaT = asin((1.0 / max(refFactor, 1e-6)) * sin(thetaI));\n"
         + "    float edgeFactor = -tan(thetaT - thetaI);\n"
         + "    if (nmerged >= refThickness) {\n"
         + "        edgeFactor = 0.0;\n"
         + "    } else {\n"
         + "        edgeFactor *= 1.0 - smoothstep(refThickness * 0.6, refThickness, nmerged);\n"
         + "    }\n"
         + "    vec2 refrOffset = -normal * edgeFactor * 0.08 * vec2(inSize.y / inSize.x, 1.0);\n"
         + "    vec4 blurred = sampleBlur(blurIndex, uvPix + refrOffset);\n"
         + "    vec4 dispPixel;\n"
         + "    {\n"
         + "        const float NR = 0.985;\n"
         + "        const float NG = 1.000;\n"
         + "        const float NB = 1.015;\n"
         + "        dispPixel.r = sampleBlur(blurIndex, uvPix + refrOffset * (1.0 - (NR - 1.0) * refDisp)).r;\n"
         + "        dispPixel.g = sampleBlur(blurIndex, uvPix + refrOffset * (1.0 - (NG - 1.0) * refDisp)).g;\n"
         + "        dispPixel.b = sampleBlur(blurIndex, uvPix + refrOffset * (1.0 - (NB - 1.0) * refDisp)).b;\n"
         + "        dispPixel.a = 1.0;\n"
         + "    }\n"
         + "    vec4 outColor = mix(dispPixel, vec4(tint.rgb, 1.0), tint.a * 0.8);\n"
         + "    float fresnelFactor = clamp(pow(1.0 + merged * inSize.y / 1500.0 * pow(500.0 / max(refFresRange, 1e-6), 2.0) + refFresHard, 5.0), 0.0, 1.0);\n"
         + "    vec3 fresTint = mix(vec3(1.0), tint.rgb, tint.a * 0.5);\n"
         + "    outColor = mix(outColor, vec4(fresTint, 1.0), fresnelFactor * refFresFac * 0.7 * nlen);\n"
         + "    float glareGeo = clamp(pow(1.0 + merged * inSize.y / 1500.0 * pow(500.0 / max(glareRange, 1e-6), 2.0) + glareHard, 5.0), 0.0, 1.0);\n"
         + "    vec3 glareMix = mix(blurred.rgb, tint.rgb, tint.a * 0.5);\n"
         + "    outColor.rgb = mix(outColor.rgb, glareMix, 0.25 * glareGeo * nlen);\n"
         + "    float edgeProx = exp(-abs(merged) * inSize.y / 9.0);\n"
         + "    if (hoverK > 0.0001) {\n"
         + "        vec2 tdir = normalize(vec2(-normal.y, normal.x));\n"
         + "        float refBoost = 1.0 + 0.35 * hoverK * edgeProx;\n"
         + "        vec2 refrHover = -normal * edgeFactor * 0.08 * refBoost * vec2(inSize.y / inSize.x, 1.0);\n"
         + "        vec2 chromaT = tdir * 0.0008 * hoverK * edgeProx * vec2(inSize.y / inSize.x, 1.0);\n"
         + "        vec3 subtle = vec3(\n"
         + "            sampleBlur(blurIndex, uvPix + refrHover + chromaT).r,\n"
         + "            sampleBlur(blurIndex, uvPix + refrHover).g,\n"
         + "            sampleBlur(blurIndex, uvPix + refrHover - chromaT).b\n"
         + "        );\n"
         + "        vec3 add = mix(subtle, vec3(1.0), 0.08) * (0.15 + 0.35 * edgeProx) * hoverK;\n"
         + "        outColor.rgb = clamp(outColor.rgb + add, 0.0, 1.0);\n"
         + "    }\n"
         + "    if (focusK > 0.0001) {\n"
         + "        vec4 rc = Rects[idx];\n"
         + "        vec2 centerPx = vec2(rc.x + 0.5 * rc.z, rc.y + 0.5 * rc.w);\n"
         + "        vec2 v = (coord - centerPx) / inSize.y;\n"
         + "        float phi = atan(v.y, v.x);\n"
         + "        float phi0 = Time * FocusBorderSpeed;\n"
         + "        float c = 0.5 + 0.5 * cos(phi - phi0);\n"
         + "        float sweep = smoothstep(0.75, 1.0, c);\n"
         + "        float mergedPx = merged * inSize.y;\n"
         + "        float w = max(FocusBorderWidthPx, 1e-3);\n"
         + "        float outside = step(0.0, mergedPx);\n"
         + "        float band = exp(-pow(max(0.0, mergedPx) / w, 2.0)) * outside;\n"
         + "        float intensity = FocusBorderIntensity * focusK;\n"
         + "        vec3 ringTint = mix(vec3(1.0), tint.rgb, 0.2);\n"
         + "        vec3 ring = ringTint * (band * sweep) * intensity;\n"
         + "        outColor.rgb = clamp(outColor.rgb + ring, 0.0, 1.0);\n"
         + "    }\n"
         + "    vec3 finalCol = mix(outColor.rgb, baseShadowed, smoothstep(-0.001, 0.001, merged));\n"
         + "    finalCol = mix(base, finalCol, clamp(extra.w, 0.0, 1.0));\n"
         + "    fragColor = vec4(finalCol, 1.0);\n"
         + "}\n";
}
